### ISSUE TITLE
STM32F411

### ISSUE THREAD

**Issue by DanielTelles91** [vibr77/AppleIISDiskII_stm32f401#1]
Hello.
First of all, thank you for this incredible project. I am interested in assembling this project on my protoboard. I have doubts about the microcontroller. Can I invest in the STM32F411 model (in the forum I saw that you are using this model) or can I buy the STM32F401? 
Thank you.
Daniel

**Comment by vibr77** [comment]
Hello Daniel, 
I suggest you go for the STM32F411 as it has SDIO port. The STMF401 does not have a SDIO port. 
I will update soon the PCB with the latest update (74LS125 to protect the STM32, PWR port for the screen, ...).

I will let you know when it is ready, should not be long. 

Vincent

**Comment by DanielTelles91** [comment]
Hello Vincent. I recently built the language card and I am having the same freezing problem. Have you figured out how to fix the problem? Could we talk via email? Thanks. 

daniel.telles91@yahoo.com
